### ISSUE TITLE
TypeError: Cannot read property 'toCSS' of undefined

### ISSUE THREAD

**Issue by StfBauer** [mrmlnc/vscode-csscomb#52]
This error I get when I try to use CSS Comb 4.0.0.
I also attached the csscomb.json

[csscomb.txt](https://github.com/mrmlnc/vscode-csscomb/files/653535/csscomb.txt)

Thanks in advance one again.

**Comment by mrmlnc** [comment]
Hello, @StfBauer,

This config correctly worked before the upgrade to the new version? Can you give me file that causes this error?

**Comment by StfBauer** [comment]
Ok got it should be solved. Your `useLatestCode` option was the problem. Well not really but gave me some ideas. Some time back you told me to set a special option because I had an issue with css comb.
In the user settings I had defined:

```
...
 "csscomb.useLegacyCore": true,
...
```

I switched it to:

```
...
"csscomb.useLegacyCode": false
...
```

Now it seams to work perfectly. Will test it during the day and if it works now I'll close the issue.

Thanx for the headsup.

**Comment by StfBauer** [comment]
Works now. Don't have any problem anymore.

**Comment by mrmlnc** [comment]
Unfortunately, the CSSComb project is no longer being developed and no fixes bugs.

It turns out that part of the bugs fixed in the new version (`useLatestCore: true`), but there are new bugs. Alas, here we can just switch the core by `useLatestCore` option.

If you use Sass with SCSS syntax or CSS then you can use [stylefmt](https://github.com/morishitter/stylefmt) based on PostCSS. Also I create VS Code plugin for it [vscode-stylefmt](https://github.com/mrmlnc/vscode-stylefmt).

**Comment by StfBauer** [comment]
Hi,
CSSComb is still maintained but the only plugin you use is not.
They rebuilt it form scratch with nodejs and now they even removed the deprecation warning: https://github.com/csscomb/csscomb.js

**Comment by mrmlnc** [comment]
In the CSSComb repository contains CSSComb 4.0.0-alpha. You can use it with `useLatestCore` option. But this is **alpha** and she has a lot of bugs.

![image](https://cloud.githubusercontent.com/assets/7034281/21342763/ad61f8b8-c6a4-11e6-81ed-eefc2713ea88.png)
